# Wrangler configuration for Cloudflare Pages
name = "wedding-platform"
compatibility_date = "2024-08-10"

[build]
command = "npm run build:deploy"
cwd = "."
watch_dir = "client/src"

[build.upload]
format = "directory"
dir = "client/dist"

[[redirects]]
from = "/api/*"
to = "/api/:splat"
status = 200

[[redirects]]
from = "/*"
to = "/index.html"
status = 200

[env.production]
vars = { NODE_ENV = "production" }

[env.staging]
vars = { NODE_ENV = "staging" }